# General
alias tl='trash-list'
alias te='trash-empty'
alias ls='lsd'
alias c='clear'
alias e='exit'
alias rm='rm -v'
alias mkdir='mkdir -v'
alias mv='mv -v'
alias cp='cp -v'
alias se='ddgr -n 5'
alias duck='w3m -4 https://lite.duckduckgo.com/lite'
alias yt='ytfzf'
alias weather='curl wttr.in/Culiacan\?m\&format=3'
alias clock='tty-clock -c -s -b'
alias suse='sudo zypper refresh && sudo zypper update && sudo zypper dup'
alias off='systemctl poweroff'
alias restart='systemctl reboot'
alias python='python3'
alias angeles='ivpn connect -l "us-ca.wg.ivpn.net"'
alias vegas='ivpn connect -l "us-nv.wg.ivpn.net"'
alias gemma='ollama run gemma2:2b --verbose'
alias llama='ollama run llama3.1 --verbose'
