db_path                 = "~/.local/share/omm/omm.db"
tl_color                = "#e78284"
atl_color               = "#85c1dc"
title                   = "To-Do's"
list_density            = "spacious"
show_context            = true
editor                  = "nvim"
confirm_before_deletion = true
circular_nav            = true
